/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/328c9bca-6fd5-41d7-acf6-e27494944148

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String message;
  int pcount;
  bool auto_Manual;
  bool light;
  bool lightSwitch;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const int ir2 = 35 ;
const int ir1 = 22 ;
const int ledpin = 17 ;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  message="Hi"  ;
  message = "Welcome" ;
  // Defined in thingProperties.h
  initProperties();
  pinMode(ir2, INPUT) ;
  pinMode(ir1, INPUT) ;



  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here

  int s1 = digitalRead(ir1) ;
  int s2 = digitalRead(ir2) ;

  if (s1 == 0)
  {
    pcount++ ;
    delay(1000) ;
    Serial.println("IN") ;
  }
  if (s2 == 0)
  {
    pcount-- ;
    delay(1000) ;
    Serial.println("OUT") ;
  }

if(auto_Manual==0)   //Auto Mode
{
  if(pcount>0)
  {
    light=1 ;
    lightSwitch=1 ;
    analogWrite(ledpin,255);
  }  
  else if(pcount<0) pcount=0 ;
  else 
  {
    light=0 ;
    lightSwitch=0 ;
    analogWrite(ledpin,0);
  }
} 
  
else if(auto_Manual==1)   //Manual Mode
{
  if(lightSwitch==1)
  {
    light=1 ;
    analogWrite(ledpin,255);
  }
  if(lightSwitch==0)
  {
    light=0 ;
    analogWrite(ledpin,0);
  }
}


}

/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change

}
/*
  Since Pcount is READ_WRITE variable, onPcountChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPcountChange()  {
  // Add your code here to act upon Pcount change
 
}

/*
  Since AutoManual is READ_WRITE variable, onAutoManualChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAutoManualChange()  {
  // Add your code here to act upon AutoManual change
  if(auto_Manual==0)
  {
    message="System in AUTO mode " ;
  }
  else message="System in MANUAL mode" ;
}

/*
  Since Message is READ_WRITE variable, onMessageChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMessageChange()  {
  // Add your code here to act upon Message change
}

/*
  Since LightSwitch is READ_WRITE variable, onLightSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightSwitchChange()  {
  // Add your code here to act upon LightSwitch change
if(auto_Manual==0)
{
  message="!!Switch to manual mode to access Switch!!" ;
}
}
